{
    #When is altitude reached
    altitude_reached_margin: 0.1,
    #Default blind hover altitude
    blind_hover_altitude: 1.0,
    #When is a destination reached
    dest_reached_margin: 0.2,
    #Topic for publishing error messages
    fsm_error_topic: control/fsm/on_error, 
    #Topic for publishing info messages
    fsm_info_topic: control/fsm/on_info, 
    #Topic for publishing current state
    fsm_state_changed_topic: control/fsm/state_changed,
    #Topic for publishing warning messages
    fsm_warn_topic: control/fsm/on_warn, 
    #Altitude for optimal gb detection
    gb_search_altitude: 2.5, 
    #Time to wait before automatic landing
    goto_hold_dest_time: 0.5,
    #Topic for recieving land detector data
    land_detector_topic: /mavros/extended_state,
    #Land detector type
    land_detector_type: landing_gear,
    #Topic for recieving lidar info
    lidar_topic: /perception/obstacles/lidar,
    #Topic for recieving local velocity estimates
    local_velocity_topic: /mavros/local_position/velocity,
    #Topic for recieving local position estimates
    local_position_topic: /mavros/local_position/pose, 
    #Topic for recieving mavros state
    mavros_state_topic: /mavros/state,
    #When is message considered old?
    message_timeout: 2.0, 
    #For what distances is it uneccesary to adjust yaw
    no_yaw_correct_dist: 0.2, 
    #Safety distance 
    obstacle_too_close_dist: 2.0, 
    #Require all data streams to enable FSM
    require_all_streams: true,
    #Require obstacle detection 
    require_obs_detection: true, 
    #Safe altitude for hovering
    safe_hover_alt: 1.0, 
    #Margin to determine if we're close enough to setpoint
    setp_reached_margin: 0.2, 
    #Buffersize for status messages
    status_msg_buffer_size: 10,
    #Takeoff altitude
    takeoff_altitude: 1.0, 
    #Margin to determine if we're close enough to yaw setpoint
    yaw_reached_margin: 0.02,
    #Altitude for goto in landxy
    land_xy_goto_alt: 1.0,
    #Minimum flying altitude
    min_in_air_alt: 0.5,
    #Topic for recieving obstacle state data
    obstacle_state_topic: perception/obstacles,
    #Margin to determine if velocity is reached
    velocity_reached_margin: 0.2
}
