{
    #When is altitude reached
    altitude_reached_margin: 0.1,
    #Default blind hover altitude
    blind_hover_altitude: 1.0,
    #Safe altitude for hovering
    safe_hover_alt: 1.0, 
    #When is a destination reached
    dest_reached_margin: 0.2,
    #Topic for publishing error messages
    fsm_error_topic: control/fsm/on_error,
    #Topic for publishing info messages
    fsm_info_topic: control/fsm/on_info,
    #Topic for publishing current state
    fsm_state_changed_topic: control/fsm/state_changed,
    #Topic for publishing warning messages
    fsm_warn_topic: control/fsm/on_warn,
    #Altitude for optimal gb detection
    gb_search_altitude: 1.0, 
    #Time to wait before automatic landing
    goto_hold_dest_time: 0.5,
    #Topic for recieving land detector data
    land_detector_topic: /land_detector,
    #Land detector type - landing_gear or mavros_extended_state
    land_detector_type: landing_gear,
    #Topic for recieving lidar info
    lidar_topic: /perception/obstacles/lidar,
    #Topic for recieving local velocity estimates
    local_velocity_topic: /mavros/local_position/velocity,
    #Topic for recieving local position estimates
    local_position_topic: /mavros/local_position/pose, 
    #Topic for recieving distance data
    distance_sensor_topic: /mavros/distance_sensor/hrlv_ez4_pub,
    #Topic for recieving mavros state
    mavros_state_topic: /mavros/state,
    #Topic for debug server
    debug_server_topic: /control/fsm/debug_server,
    #Topic for action server
    action_server_topic: /control/fsm/action_server,
    #When is message considered old?
    message_timeout: 2.0,
    #For what distances is it uneccesary to adjust yaw
    no_yaw_correct_dist: 0.2,
    #Safety distance
    obstacle_too_close_dist: 2.0,
    #Require all data streams to enable FSM
    require_all_streams: true,
    #Require obstacle detection
    require_obs_detection: true,
    #Safe altitude for hovering
    safe_hover_alt: 1.0,
    #Margin to determine if we're close enough to setpoint
    setp_reached_margin: 0.2, 
    #Buffersize for status messages
    status_msg_buffer_size: 10,
    #Takeoff altitude
    takeoff_altitude: 1.0,
    #Margin to determine if we're close enough to yaw setpoint
    yaw_reached_margin: 0.02,
    #Altitude for goto in landxy
    land_xy_goto_alt: 1.0,
    #Minimum flying altitude
    min_in_air_alt: 0.5,
    #Topic for recieving obstacle state data
    obstacle_state_topic: perception/obstacles/lidar,
    #Margin to determine if velocity is reached
    velocity_reached_margin: 0.2,
    #Path planner client topic
    path_planner_client_topic: /path_planner_service,
    #Path planner plan topic
    path_planner_plan_topic: /control/planner/plan,
    #Path planner timeout
    path_plan_timeout: 1.0,
    #Obstacle avoidance clearance 
    obstacle_clearance_max: 1.1,
    obstacle_clearance_min: 1.0,
    #Obstacle avoidance checkradius
    obstacle_clearance_checkradius: 40.0,
    #Frame ID for global frame
    global_frame_id: map,
    #Frame ID for local frame
    local_frame_id: odom,
    #Use global to local transforms
    use_global_transforms: true,
    #Restrict arena boundaries
    restrict_arena_boundaries: true,
    #Lowest allowed global x position
    arena_lowest_x: 0.0,
    #Lowest allowed global y position
    arena_lowest_y: 0.0,
    #Highest allowed global x position
    arena_highest_x: 20.0,
    #Highest allowed global y position
    arena_highest_y: 20.0,
    #Require use of distance sensor
    require_distance_sensor: true
}
